# Generated by Django 4.2.13 on 2024-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloguser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='blog_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=20),
        ),
    ]
