# Generated by Django 4.2.13 on 2024-06-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_createblog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='blog_type',
            field=models.CharField(choices=[('P', 'Private'), ('P', 'Public')], default='Public', max_length=20),
        ),
    ]
