# Generated by Django 4.2.13 on 2024-06-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_createblog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='blog_type',
            field=models.CharField(choices=[('P', 'Private'), ('S', 'Public')], default='S', max_length=20),
        ),
    ]
